### ISSUE TITLE
BOM part number 25 value is not defined

### ISSUE THREAD

**Issue by jacktronics** [x86fr/ATX2AT-Smart-Converter#1]
The capacitor C14 / C16 have a non defined value, still listed as TBD, can you update it with the final value please ?

**Comment by x86fr** [comment]
Sure. And there is also some minors changes on the BOM. I will commit the final version within one hour.

The 1.12 firmware is also bugged (typo on +12V over-current detection). The final FW that shipped is 1.13. I will upload it tomorrow

**Comment by x86fr** [comment]
Fixed!

**Comment by jacktronics** [comment]
Thanks, the BOM looks better now, thanks for uploading the newer firmware too. closing this issue.
