### ISSUE TITLE
Missing Q3 on schematic

### ISSUE THREAD

**Issue by jarzebski** [x86fr/ATX2AT-Smart-Converter#10]
Hi, I'm trying to find Q3 (2N7002DW) on schematic. Is actual?

**Comment by x86fr** [comment]
Hi, It's a Dual Channel MOSFET. Here are the two MOSFETs  from Q3 on the schematics :

![image](https://user-images.githubusercontent.com/38105886/216788422-d745efe7-c5ea-4358-a8c2-afa3d164f1e9.png)
